#pragma once

#define INSTRUMENTATION_PREFIX __instrumentation
#define _INSTRUMENTATION_STR(X) #X
#define INSTRUMENTATION_STR(X) _INSTRUMENTATION_STR(X)
#define INSTRUMENTATION_PREFIX_STR INSTRUMENTATION_STR(INSTRUMENTATION_PREFIX)
#define CHECK_ZERO_PREFIX "_check_zero_"
#define ALLOCATE_BUFFER_PREFIX "__allocate_zero_buffer"